[package]
name = "commando"
version = "0.0.0"
edition = "2021"
description = "A CLI tool that help you write conventional commit messages interactively."
license = "GNU General Public License v3.0"

[dependencies]
