[package]
name = "commando"
version = "0.2.0"
authors = ["Hammed Anuoluwapo Pelumi <stationphast@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
